#URI: "https://ShabiBaig@bitbucket.org/posmachineteam/ezygentechnology-pos.git"
#destinationDirectoryPath: "C:\\SpeedUP\\SpeedUP\\ShabiPOS2"

URI: "C:\\SpeedUP\\SpeedUP\\ShabiPOS"
destinationDirectoryPath: "C:\\SpeedUP\\SpeedUP\\Test"

